services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls.certresolver=le"

  portainer:
    image: portainer/portainer-ce:2.18.4
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - EXTENSIONS=/extensions/reverse-proxy
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
      - "./portainer-extension:/extensions/reverse-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.domain=portainer.${DOMAIN}"

  dns-watcher:
    build: ./dns-sync
    container_name: dns-watcher
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config:/config"
    restart: always

  control-panel:
    build: ./control-panel
    container_name: control-panel
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config:/config"
    environment:
      DOMAIN: "${DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.control.rule=Host(`control.${DOMAIN}`)"
      - "traefik.http.routers.control.entrypoints=websecure"
      - "traefik.http.routers.control.tls.certresolver=le"
      - "traefik.domain=control.${DOMAIN}"

volumes:
  portainer_data:
